# Project information
site_name: Tekton 101 Workshop
site_url: https://ibm.github.io/tekton-tutorial-openshift
site_author: IBM Developer

# Repository
repo_name: tekton-tutorial-openshift
repo_url: https://github.com/IBM/tekton-tutorial-openshift
edit_uri: edit/master/docs

# Navigation
nav:
  - Welcome:
    - About the workshop: README.md
  - <b>Lab1 Tekton 101</b>:
    - Setup: lab1/0_setup.md
    - Clone Git Repo: lab1/1_clone-git-repo.md
    - Build and Push Image using Kaniko: lab1/2_build-and-push-image-using-kaniko.md
    - Deploy an Image to OpenShift: lab1/3_deploy-image-to-cluster.md
    - Create Pipeline: lab1/4_create-pipeline.md
    - Create ServiceAccount: lab1/5_create-service-account.md
    - Create PipelineRun: lab1/6_create-pipeline-run.md
    - Run the Pipeline: lab1/7_run-the-pipeline.md

## DO NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2021 IBM Developer

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: ibm_8bar_reverse_2
  features:
    - navigation.tabs
    #- navigation.instant
    - navigation.expand
  palette:
    scheme: default
    primary: black
    accent: blue
  custom_dir: overrides

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ibmdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ibm/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/developerworks
    - icon: fontawesome/brands/dev
      link: https://dev.to/ibmdeveloper

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
